//
//  BAZPaymentProtocols.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BAZPaymentWireframeProtocol: class {

}
//MARK: Presenter -
protocol BAZPaymentPresenterProtocol: class {

}

//MARK: Interactor -
protocol BAZPaymentInteractorProtocol: class {

  var presenter: BAZPaymentPresenterProtocol?  { get set }
}

//MARK: View -
protocol BAZPaymentViewProtocol: class {

  var presenter: BAZPaymentPresenterProtocol?  { get set }
}
