//
//  BAZPaymentViewController.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WalletSDK

class BAZPaymentViewController: UIViewController, BAZPaymentViewProtocol {

	var presenter: BAZPaymentPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var continueButton: UIButton!
    @IBOutlet weak var whoYouSendView: UIView!
    @IBOutlet weak var balanceLabel: UILabel!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var warningLabel: UILabel!
    @IBOutlet weak var stepViewWidth: NSLayoutConstraint!
    @IBOutlet weak var amountTextField: UITextField!

    //MARK: - Properties
    var walletInit: WalletSDKInit = WalletSDKInit.shared
    
    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        animateStepView()
        
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)

    }
    
    //MARK: - Actions
    @objc func myTextFieldDidChange(_ textField: UITextField) {
        if let amountString = textField.text?.currencyInputFormatting() {
            textField.text = amountString
        }
    }
    
    //MARK: - @IBActions
    @IBAction func removeKeyBoard(_ sender: UITapGestureRecognizer) {
        amountTextField.resignFirstResponder()
    }
    
    //MARK: - Methods
    private func setView() {
        continueButton.layer.cornerRadius = 30.0
        whoYouSendView.layer.cornerRadius = 5.0
        whoYouSendView.addShadow()
        
        let name = UserDefaults.standard.string(forKey: "destinationName")!
        let nameSplit = name.split(separator: " ")
        nameLabel.text = String(nameSplit[0]) + " " + String(nameSplit[1].first!) + "."
        
        let balance = UserDefaults.standard.double(forKey: "balance")
        balanceLabel.attributedText = "$\(String(format: "%.2f", balance))".priceStyle(fontSize: 15.0, weight: .medium)
        
        let toolBar = UIToolbar(frame: CGRect(origin: CGPoint.zero, size: CGSize(width: self.view.frame.size.width, height: 45)))
        let spaceToolBarButton = UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil)
        let doneToolBarButton = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(toolBarAction))
        toolBar.barTintColor = UIColor(red: 0.09, green: 0.58, blue: 0.28, alpha: 1.0)
        doneToolBarButton.tintColor = UIColor.white
        toolBar.items = [spaceToolBarButton, doneToolBarButton]
        amountTextField.inputAccessoryView = toolBar
        
        amountTextField.addTarget(self, action: #selector(myTextFieldDidChange), for: .editingChanged)
    }
    
    @objc private func toolBarAction() {
        amountTextField.resignFirstResponder()
    }
    
    private func animateStepView() {
        view.layoutIfNeeded()
        stepViewWidth.constant = self.view.frame.width * 0.25
        UIView.animate(withDuration: 1.0, animations: {
            self.view.layoutIfNeeded()
        })
    }
    
    private func correctNumberInTextField() {
        let view = ResumeRouter.createModule(walletInit: walletInit)
        self.navigationController?.pushViewController(view, animated: true)
        warningLabel.isHidden = true
    }
    
    //MARK: - @IBActions
    @IBAction func goToResume(_ sender: UIButton) {
        guard let textFieldText = amountTextField.text else { return }
        let balance = UserDefaults.standard.double(forKey: "balance")
        
        if textFieldText == "" {
            let amount = 200.00
            
            if amount > balance {
                warningLabel.isHidden = false
            } else {
                UserDefaults.standard.setValue("200.00", forKey: "amount")
                correctNumberInTextField()
            }
        } else {
            let text = textFieldText.replacingOccurrences(of: "$", with: "")
            let amount = Double(text)!
            
            
            if amount > balance {
                warningLabel.isHidden = false
            } else {
                UserDefaults.standard.setValue(text, forKey: "amount")
                correctNumberInTextField()
            }
        }
    }
    
    @IBAction func goBack(_ sender: UIButton) {
        self.navigationController?.popViewController(animated: true)
    }

}
