//
//  BAZPaymentPresenter.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BAZPaymentPresenter: BAZPaymentPresenterProtocol {

    weak private var view: BAZPaymentViewProtocol?
    var interactor: BAZPaymentInteractorProtocol?
    private let router: BAZPaymentWireframeProtocol

    init(interface: BAZPaymentViewProtocol, interactor: BAZPaymentInteractorProtocol?, router: BAZPaymentWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
