//
//  BAZHomeProtocols.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BAZHomeWireframeProtocol: class {

}
//MARK: Presenter -
protocol BAZHomePresenterProtocol: class {

}

//MARK: Interactor -
protocol BAZHomeInteractorProtocol: class {

  var presenter: BAZHomePresenterProtocol?  { get set }
}

//MARK: View -
protocol BAZHomeViewProtocol: class {

  var presenter: BAZHomePresenterProtocol?  { get set }
}
