//
//  BAZHomePresenter.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BAZHomePresenter: BAZHomePresenterProtocol {

    weak private var view: BAZHomeViewProtocol?
    var interactor: BAZHomeInteractorProtocol?
    private let router: BAZHomeWireframeProtocol

    init(interface: BAZHomeViewProtocol, interactor: BAZHomeInteractorProtocol?, router: BAZHomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
