//
//  WhereDoProtocols.swift
//  WalletSDK
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WhereDoWireframeProtocol: class {

}
//MARK: Presenter -
protocol WhereDoPresenterProtocol: class {

}

//MARK: Interactor -
protocol WhereDoInteractorProtocol: class {

  var presenter: WhereDoPresenterProtocol?  { get set }
}

//MARK: View -
protocol WhereDoViewProtocol: class {

  var presenter: WhereDoPresenterProtocol?  { get set }
}
