//
//  WhereDoInteractor.swift
//  WalletSDK
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WhereDoInteractor: WhereDoInteractorProtocol {

    weak var presenter: WhereDoPresenterProtocol?
}
