//
//  MenuProtocols.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 20/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MenuWireframeProtocol: AnyObject {

}

//MARK: Presenter -
protocol MenuPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol MenuInteractorProtocol: AnyObject {

  var presenter: MenuPresenterProtocol?  { get set }
}

//MARK: View -
protocol MenuViewProtocol: AnyObject {

  var presenter: MenuPresenterProtocol?  { get set }
}
