//
//  BAZAirBazViewController.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WalletSDK

class BAZAirBazViewController: UIViewController, BAZAirBazViewProtocol {

	var presenter: BAZAirBazPresenterProtocol?

    //MARK: - @IBOutlets
    @IBOutlet weak var containerView: UIView!
    @IBOutlet weak var stepViewWidth: NSLayoutConstraint!
    @IBOutlet weak var descriptionLbl: UILabel!
    
    //MARK: - Properties
    var walletInit: WalletSDKInit = WalletSDKInit.shared
    var airBazView: AirBazViewController?
    
    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
        let lat = UserDefaults.standard.double(forKey: "lat")
        let lng = UserDefaults.standard.double(forKey: "lng")
        descriptionLbl.text = "lat: \(lat), lng: \(lng)"
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        animateStepView()
    }
    
    //MARK: - Methods
    private func setView() {
        airBazView = walletInit.renderRadar(delegate: self) as? AirBazViewController
        addChild(airBazView!)
        airBazView!.view.frame = containerView.bounds
        containerView.addSubview(airBazView!.view)
    }
    
    private func animateStepView() {
        view.layoutIfNeeded()
        stepViewWidth.constant = self.view.frame.width * 0.25
        UIView.animate(withDuration: 1.0, animations: {
            self.view.layoutIfNeeded()
        })
    }
    
    @IBAction func goBack(_ sender: UIButton) {
        self.navigationController?.popViewController(animated: true)
    }
    
    @IBAction func root(_ sender: UIButton) {
        self.navigationController?.popToRootViewController(animated: true)
    }

    @IBAction func onClickChangeAccount(_ sender: Any) {
        changeAccount(accountNumber: "1234567890")
//        changeLatAndLong(latitude: 19.0489671, longitude: -99.536513)
    }
    
    func changeAccount(accountNumber: String) {
        airBazView!.changeAccountNumber(accountNumber: accountNumber)
       // walletInit.changeAccountNumber(accountNumber: accountNumber)
    }
    
    func changeLatAndLong(latitude: Double, longitude: Double) {
//        walletInit.changeLatAndLong(latitude: latitude, longitude: longitude)
        airBazView!.changeLatAndLong(latitude: latitude, longitude: longitude)
    }
    
}

//MARK: - WalletSDKDelegate
extension BAZAirBazViewController: WalletSDKDelegate {
    func decryptText(_ text: String) -> String {        
        return text.replacingOccurrences(of: "%", with: "")
    }
    
    func onError(_ errorCode: Int) {
        print("=============ERROR============")
        self.sendNotification(body: "Error codigo: \(errorCode)")
    }
    

    func sucessAtFindingDevice(name: String, apPat: String, phone: String,  accountNumber: String) {
        let completeName = name + " " + apPat
        UserDefaults.standard.setValue(completeName, forKey: "destinationName")
        UserDefaults.standard.setValue(accountNumber, forKey: "destinationNumber")
        UserDefaults.standard.setValue(phone, forKey: "destinationPhoneNumber")
        
        let view = BAZPaymentRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }

}

extension BAZAirBazViewController {
    func sendNotification(body: String) {
        let notificationContent = UNMutableNotificationContent()
        notificationContent.body = body

        let request = UNNotificationRequest(identifier: "testNotification",
                                            content: notificationContent,
                                            trigger: nil)
        
        UNUserNotificationCenter.current().add(request) { (error) in
            if let error = error {
                print("Notification Error: ", error)
            }
        }
    }
}
