//
//  BAZAirBazProtocols.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BAZAirBazWireframeProtocol: AnyObject {

}

//MARK: Presenter -
protocol BAZAirBazPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol BAZAirBazInteractorProtocol: AnyObject {
    
    var presenter: BAZAirBazPresenterProtocol?  { get set }
}

//MARK: View -
protocol BAZAirBazViewProtocol: AnyObject {
    
    var presenter: BAZAirBazPresenterProtocol?  { get set }
}
