//
//  BAZAirBazInteractor.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BAZAirBazInteractor: BAZAirBazInteractorProtocol {

    weak var presenter: BAZAirBazPresenterProtocol?
}
