//
//  BAZAirBazRouter.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WalletSDK

class BAZAirBazRouter: BAZAirBazWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = BAZAirBazViewController(nibName: "BAZAirBazViewController", bundle: nil)
        let interactor = BAZAirBazInteractor()
        let router = BAZAirBazRouter()
        let presenter = BAZAirBazPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
