//
//  TransferViewController.swift
//  WalletSDK
//
//  Created Usuario Phinder 2020 on 03/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TransferViewController: UIViewController, TransferViewProtocol {

	var presenter: TransferPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var requiredAmountLabel: UILabel!
    @IBOutlet weak var amountTextField: UITextField!
    @IBOutlet weak var transferResultLabel: UILabel!
    @IBOutlet weak var transferButton: UIButton!
    @IBOutlet weak var accountImage: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var accountLabel: UILabel!
    
    //MARK: - Properties
    var myAccountNumber: String!
    var accountToTransfer: String!
    var accountName: String!
    var accountApPat: String!
    
    //MARK: - Life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    //MARK: - @IBActions
    @IBAction func makeTransfer(_ sender: UIButton) {
        presenter?.checkTextField(amount: amountTextField.text)
    }
    
    @IBAction func hideKeyBoardInTap(_ sender: UITapGestureRecognizer) {
        amountTextField.resignFirstResponder()
    }
    
    @IBAction private func popView(_ sender: UIButton) {
        self.navigationController?.popViewController(animated: true)
    }

}

//MARK: - Private Methods
extension TransferViewController {
    private func setView() {
        let circleImage = CircleNameImage.create(name: accountName, apPat: accountApPat, color: UIColor().randomColor)
        accountImage.image = circleImage
        nameLabel.text = accountName + " " + accountApPat
        accountLabel.text = "Cuenta: " + accountToTransfer
        transferButton.setCorner(cornerRadius: 10.0)
    }
}

//MARK: - Presenter Methods
extension TransferViewController {
    func amountIsEmpty(_ isEmpty: Bool) {
        requiredAmountLabel.isHidden = isEmpty ? false : true
    }
    
    func isTextFieldWithText(amount: String) {
        presenter?.makeTransfer(amount: amount, accountToTransfer: accountToTransfer, myAccountNumber: myAccountNumber)
    }
    
    func isTransferCorrect(amount: String) {
        let view = SuccsessfulTransferRouter.createModule(accountName: accountName,
                                                          accountApPat: accountApPat,
                                                          accountToTransfer: accountToTransfer,
                                                          amount: amount)
        
        self.navigationController?.pushViewController(view, animated: true)
    }
    
    func isTransferIncorrect() {
        transferResultLabel.text = "Transferencia Incorrecta"
        transferResultLabel.isHidden = false
    }
    
}
