//
//  TransferPresenter.swift
//  WalletSDK
//
//  Created Usuario Phinder 2020 on 03/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TransferPresenter: TransferPresenterProtocol {

    weak private var view: TransferViewProtocol?
    var interactor: TransferInteractorProtocol?
    private let router: TransferWireframeProtocol

    init(interface: TransferViewProtocol, interactor: TransferInteractorProtocol?, router: TransferWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func makeTransfer(amount: String, accountToTransfer: String, myAccountNumber: String) {
        interactor?.makeTransfer(amount: amount, accountToTransfer: accountToTransfer, myAccountNumber: myAccountNumber)
    }
    
    func checkTextField(amount: String?) {
        interactor?.checkTextField(amount: amount)
    }
    
    func amountIsEmpty(_ isEmpty: Bool) {
        view?.amountIsEmpty(isEmpty)
    }
    
    func isTextFieldWithText(amount: String) {
        view?.isTextFieldWithText(amount: amount)
    }
    
    func isTransferCorrect(amount: String) {
        view?.isTransferCorrect(amount: amount)
    }
    
    func isTransferIncorrect() {
        view?.isTransferIncorrect()
    }

}
