//
//  TransferProtocols.swift
//  WalletSDK
//
//  Created Usuario Phinder 2020 on 03/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TransferWireframeProtocol: class {

}

//MARK: Presenter -
protocol TransferPresenterProtocol: class {

    func makeTransfer(amount: String, accountToTransfer: String, myAccountNumber: String)
    func checkTextField(amount: String?)
    func amountIsEmpty(_ isEmpty: Bool)
    func isTextFieldWithText(amount: String)
    func isTransferCorrect(amount: String)
    func isTransferIncorrect()
}

//MARK: Interactor -
protocol TransferInteractorProtocol: class {
    
    var presenter: TransferPresenterProtocol?  { get set }
    
    func makeTransfer(amount: String, accountToTransfer: String, myAccountNumber: String)
    func checkTextField(amount: String?)
}

//MARK: View -
protocol TransferViewProtocol: class {
    
    var presenter: TransferPresenterProtocol?  { get set }
    
    func amountIsEmpty(_ isEmpty: Bool)
    func isTextFieldWithText(amount: String)
    func isTransferCorrect(amount: String)
    func isTransferIncorrect()
}
