//
//  FinalDetailInteractor.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FinalDetailInteractor: FinalDetailInteractorProtocol {

    weak var presenter: FinalDetailPresenterProtocol?
}
