//
//  FinalDetailRouter.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AirBaz

class FinalDetailRouter: FinalDetailWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(walletInit: AirBazInit) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FinalDetailViewController(nibName: "FinalDetailViewController", bundle: nil)
        view.walletInit = walletInit
        
        let interactor = FinalDetailInteractor()
        let router = FinalDetailRouter()
        let presenter = FinalDetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
