//
//  FinalDetailProtocols.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FinalDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol FinalDetailPresenterProtocol: class {

}

//MARK: Interactor -
protocol FinalDetailInteractorProtocol: class {

  var presenter: FinalDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol FinalDetailViewProtocol: class {

  var presenter: FinalDetailPresenterProtocol?  { get set }
}
