//
//  FinalDetailPresenter.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FinalDetailPresenter: FinalDetailPresenterProtocol {

    weak private var view: FinalDetailViewProtocol?
    var interactor: FinalDetailInteractorProtocol?
    private let router: FinalDetailWireframeProtocol

    init(interface: FinalDetailViewProtocol, interactor: FinalDetailInteractorProtocol?, router: FinalDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
