//
//  ChooseAmountRouter.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 20/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChooseAmountRouter: ChooseAmountWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ChooseAmountViewController(nibName: "ChooseAmountViewController", bundle: nil)
        let interactor = ChooseAmountInteractor()
        let router = ChooseAmountRouter()
        let presenter = ChooseAmountPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
