//
//  ChooseAmountProtocols.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 20/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ChooseAmountWireframeProtocol: AnyObject {

}

//MARK: Presenter -
protocol ChooseAmountPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol ChooseAmountInteractorProtocol: AnyObject {
    
    var presenter: ChooseAmountPresenterProtocol?  { get set }
}

//MARK: View -
protocol ChooseAmountViewProtocol: AnyObject {
    
    var presenter: ChooseAmountPresenterProtocol?  { get set }
}
