//
//  ChooseAmountViewController.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 20/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChooseAmountViewController: UIViewController, ChooseAmountViewProtocol {

	var presenter: ChooseAmountPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var headerView: UIView!
    @IBOutlet weak var contentView: UIView!

    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    //MARK: - Methods
    private func setView() {
        headerView.roundCorners(corners: [.layerMinXMaxYCorner, .layerMaxXMaxYCorner], cornerRadius: 30.0)
        contentView.setCorner(cornerRadius: 15.0)
    }

}
