//
//  InitPresenter.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class InitPresenter: InitPresenterProtocol {

    weak private var view: InitViewProtocol?
    var interactor: InitInteractorProtocol?
    private let router: InitWireframeProtocol

    init(interface: InitViewProtocol, interactor: InitInteractorProtocol?, router: InitWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
