//
//  InitViewController.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 05/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AirBaz

class InitViewController: UIViewController, InitViewProtocol {

	var presenter: InitPresenterProtocol?

    //MARK: - @IBOutlets
    @IBOutlet weak var containerView: UIView!
    
    //MARK: - Properties
    var name: String!
    var apPat: String!
    var accountNumber: String!
    var color: Color!
    
    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    //MARK: - Methods
    private func setView() {
//        let wallet = WalletSDKInit()
//        let airBazView = wallet.renderRadar(delegate: self,
//                                            accountNumber: accountNumber,
//                                            name: name,
//                                            apPat: apPat,
//                                            latitude: 19.3047057,
//                                            longitude: -99.2037942,
//                                            radioColor: color.color,
//                                            selfColor: color.color)
//        
//        addChild(airBazView)
//        airBazView.view.frame = containerView.bounds
//        containerView.addSubview(airBazView.view)
    }
    
    //MARK: - @IBActions
    @IBAction private func popView(_ sender: UIButton) {
        self.navigationController?.popToRootViewController(animated: true)
    }

}
