//
//  InitViewController.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WalletSDK

class InitViewController: UIViewController, InitViewProtocol {

	var presenter: InitPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var containerView: UIView!
    
    //MARK: - Properties
    var name: String!
    var surname: String!
    var accountNumber: String!

    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    //MARK: - Methods
    func setView() {
        let rechability = false
        let airBazView = WalletSDKInit.openWallet(rechability: rechability,
                                                  accountNumber: accountNumber,
                                                  name: name,
                                                  apPat: surname,
                                                  latitude: 19.3047057,
                                                  longitude: -99.2037942,
                                                  userName: "hgonzalez",
                                                  phone: 5510518955,
                                                  radioColor: "#117243",
                                                  selfColor: "#2C7B89")
        
        addChild(airBazView)
        airBazView.view.frame = containerView.bounds
        containerView.addSubview(airBazView.view)
    }

}
