//
//  ResumeRouter.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AirBaz

class ResumeRouter: ResumeWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(walletInit: AirBazFacade) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ResumeViewController(nibName: "ResumeViewController", bundle: nil)
        view.walletInit = walletInit
        
        let interactor = ResumeInteractor()
        let router = ResumeRouter()
        let presenter = ResumePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
