//
//  ResumeProtocols.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ResumeWireframeProtocol: class {

}
//MARK: Presenter -
protocol ResumePresenterProtocol: class {

}

//MARK: Interactor -
protocol ResumeInteractorProtocol: class {

  var presenter: ResumePresenterProtocol?  { get set }
}

//MARK: View -
protocol ResumeViewProtocol: class {

  var presenter: ResumePresenterProtocol?  { get set }
}
