//
//  ResumePresenter.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ResumePresenter: ResumePresenterProtocol {

    weak private var view: ResumeViewProtocol?
    var interactor: ResumeInteractorProtocol?
    private let router: ResumeWireframeProtocol

    init(interface: ResumeViewProtocol, interactor: ResumeInteractorProtocol?, router: ResumeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
