//
//  ResumeViewController.swift
//  AirBazGeneric
//
//  Created Branchbit on 21/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AirBaz

class ResumeViewController: UIViewController, ResumeViewProtocol {
    
	var presenter: ResumePresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var continueButton: UIButton!
    @IBOutlet weak var balanceLabel: UILabel!
    @IBOutlet weak var amountLabel: UILabel!
    @IBOutlet weak var stepViewWidth: NSLayoutConstraint!
    @IBOutlet weak var nameLabel: UILabel!
    
    //MARK: - Properties
    var walletInit: AirBazInit!

    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        animateStepView()
    }
    
    //MARK: - Methods
    private func setView() {
        continueButton.layer.cornerRadius = 30.0
        
        let name = UserDefaults.standard.string(forKey: "destinationName")!
        let nameSplit = name.split(separator: " ")
        nameLabel.text = String(nameSplit[0]) + " " + String(nameSplit[1].first!) + "."

        let balance = UserDefaults.standard.double(forKey: "balance")
        balanceLabel.attributedText = "$\(String(format: "%.2f", balance))".priceStyle(fontSize: 16.0, weight: .regular)

        let amount = UserDefaults.standard.double(forKey: "amount")
        amountLabel.attributedText = "$\(String(format: "%.2f", amount))".priceStyle(fontSize: 17.0, weight: .bold)
    }
    
    private func animateStepView() {
        view.layoutIfNeeded()
        stepViewWidth.constant = self.view.frame.width * 0.25
        UIView.animate(withDuration: 1.0, animations: {
            self.view.layoutIfNeeded()
        })
    }
    
    //MARK: - @IBActions
    @IBAction func goBack(_ sender: UIButton) {
        self.navigationController?.popViewController(animated: true)

    }
    
    @IBAction func goToFinalDetail(_ sender: UIButton) {
        let view = FinalDetailRouter.createModule(walletInit: walletInit)
        self.navigationController?.pushViewController(view, animated: true)
    }

}
