//
//  SuccsessfulTransferRouter.swift
//  WalletSDK
//
//  Created Usuario Phinder 2020 on 03/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SuccsessfulTransferRouter: SuccsessfulTransferWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(accountName: String, accountApPat: String, accountToTransfer: String, amount: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SuccsessfulTransferViewController(nibName: "SuccsessfulTransferViewController", bundle: nil)
        view.accountToTransfer = accountToTransfer
        view.accountName = accountName
        view.accountApPat = accountApPat
        view.amount = amount
        
        let interactor = SuccessfulTransferInteractor()
        let router = SuccsessfulTransferRouter()
        let presenter = SuccsessfulTransferPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
