//
//  SuccsessfulTransferViewController.swift
//  WalletSDK
//
//  Created Usuario Phinder 2020 on 03/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SuccsessfulTransferViewController: UIViewController, SuccsessfulTransferViewProtocol {

	var presenter: SuccsessfulTransferPresenterProtocol?

    //MARK: - @IBOutlets
    @IBOutlet weak var amountLabel: UILabel!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var accountLabel: UILabel!
    @IBOutlet weak var continueButton: UIButton!
    @IBOutlet weak var containerView: UIView!
    
    //MARK: - Properties
    var accountToTransfer: String!
    var accountName: String!
    var accountApPat: String!
    var amount: String!
    
    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    //MARK: - @IBActions
    @IBAction func continueAction(_ sender: UIButton) {
        self.navigationController?.popToRootViewController(animated: true)
    }

}

//MARK: - Private Methods
extension SuccsessfulTransferViewController {
    func setView() {
        containerView.setCorner(cornerRadius: 10.0)
        continueButton.setCorner(cornerRadius: 10.0)
        containerView.addShadow()
        nameLabel.text = accountName + " " + accountApPat
        accountLabel.text = "Cuenta: " + accountToTransfer
        amountLabel.text = "$ " + amount
    }
}
