//
//  LoginPresenter.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 30/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {

    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func checkTextFields(nameText: String?, surnameText: String?, accountNumber: String?) {
        interactor?.checkTextFields(nameText: nameText, surnameText: surnameText, accountNumber: accountNumber)
    }
    
    func nameIsEmpty(_ isEmpty: Bool) {
        view?.nameIsEmpty(isEmpty)
    }
    
    func surnameIsEmpty(_ isEmpty: Bool) {
        view?.surnameIsEmpty(isEmpty)
    }
    
    func accountNumberIsEmpty(_ isEmpty: Bool) {
        view?.accountNumberIsEmpty(isEmpty)
    }
    
    func areTextFieldsWithText(name: String, surname: String, accountNumber: String) {
        view?.areTextFieldsWithText(name: name, surname: surname, accountNumber: accountNumber)
    }

}
