//
//  LoginViewController.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 30/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {

	var presenter: LoginPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var surnameTextField: UITextField!
    @IBOutlet weak var accountNumberTextField: UITextField!
    @IBOutlet weak var requiredNameLabel: UILabel!
    @IBOutlet weak var requiredApPatLabel: UILabel!
    @IBOutlet weak var requiredAccountNumberLabel: UILabel!
    @IBOutlet weak var discoverButton: UIButton!

    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        setView()
    }
    
    //MARK: - Methods
    private func setView() {
        discoverButton.setCorner(cornerRadius: 10.0)
        nameTextField.delegate = self
        surnameTextField.delegate = self
        accountNumberTextField.delegate = self
    }
    
    private func hideKeyboard() {
        nameTextField.resignFirstResponder()
        surnameTextField.resignFirstResponder()
        accountNumberTextField.resignFirstResponder()
        ViewAnimation.init(y: 0, viewMove: self.view).animation()
    }
    
    //MARK: - @IBActions
    @IBAction func hideKeyBoardInTap(_ sender: UITapGestureRecognizer) {
        hideKeyboard()
    }
    
    @IBAction func discoverAction(_ sender: UIButton) {
        hideKeyboard()
        presenter?.checkTextFields(nameText: nameTextField.text, surnameText: surnameTextField.text, accountNumber: accountNumberTextField.text)
    }

}

//MARK: - UITextFieldDelegate
extension LoginViewController: UITextFieldDelegate {
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        if textField == accountNumberTextField {
            guard let textFieldText = textField.text, let rangeOfTextToReplace = Range(range, in: textFieldText) else { return false }
            let substringToReplace = textFieldText[rangeOfTextToReplace]
            let count = textFieldText.count - substringToReplace.count + string.count
            return count <= 14
        }
        
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        switch textField {
        case nameTextField:
            ViewAnimation.init(y: -50, viewMove: self.view).animation()
        case surnameTextField:
            ViewAnimation.init(y: -100, viewMove: self.view).animation()
        case accountNumberTextField:
            ViewAnimation.init(y: -150, viewMove: self.view).animation()
        default:
            break
        }
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        switch textField {
        case nameTextField:
            surnameTextField.becomeFirstResponder()
        case surnameTextField:
            accountNumberTextField.becomeFirstResponder()
        default:
            hideKeyboard()
        }
        
        return true
    }
    
}

//MARK: - Presenter Methods
extension LoginViewController {
    func nameIsEmpty(_ isEmpty: Bool) {
        requiredNameLabel.isHidden = isEmpty ? false : true
    }
    
    func surnameIsEmpty(_ isEmpty: Bool) {
        requiredApPatLabel.isHidden = isEmpty ? false : true
    }
    
    func accountNumberIsEmpty(_ isEmpty: Bool) {
        requiredAccountNumberLabel.isHidden = isEmpty ? false : true
    }
    
    func areTextFieldsWithText(name: String, surname: String, accountNumber: String) {
        let initView = InitRouter.createModule() as! InitViewController
        initView.name = name
        initView.surname = surname
        initView.accountNumber = accountNumber
        self.navigationController?.pushViewController(initView, animated: true)
    }
}
