//
//  LoginProtocols.swift
//  AirBazGeneric
//
//  Created Usuario Phinder 2020 on 30/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginWireframeProtocol: AnyObject {

}

//MARK: Presenter -
protocol LoginPresenterProtocol: AnyObject {

    func checkTextFields(nameText: String?, surnameText: String?, accountNumber: String?)
    func nameIsEmpty(_ isEmpty: Bool)
    func surnameIsEmpty(_ isEmpty: Bool)
    func accountNumberIsEmpty(_ isEmpty: Bool)
    func areTextFieldsWithText(name: String, surname: String, accountNumber: String)
}

//MARK: Interactor -
protocol LoginInteractorProtocol: AnyObject {
    
    var presenter: LoginPresenterProtocol?  { get set }
    
    func checkTextFields(nameText: String?, surnameText: String?, accountNumber: String?)
}

//MARK: View -
protocol LoginViewProtocol: AnyObject {
    
    var presenter: LoginPresenterProtocol?  { get set }
    
    func nameIsEmpty(_ isEmpty: Bool)
    func surnameIsEmpty(_ isEmpty: Bool)
    func accountNumberIsEmpty(_ isEmpty: Bool)
    func areTextFieldsWithText(name: String, surname: String, accountNumber: String)
}
